### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ewgcat** [2BAB/ScratchPaper#4] opened 2018-10-10 12:42 UTC
nkerSupport gen AndroidManifest.xml in build/intermediates/bugly_intermediates/AndroidManifest.xml
:app:tinkerSupportProcessSittestDebugManifest
:app:processSittestDebugResources
invalid resource directory name: /Users/lishuaihua/Desktop/YiJianStaff/app/build/intermediates/res/merged/sittest/debug mipmap-xxhdpi-v4_ic_launcher.png.flat
:app:processSittestDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processSittestDebugResources'.
> Failed to process resources, see aapt output above for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
51 actionable tasks: 47 executed, 4 up-to-date

**Comment by 2BAB** [comment] 2018-10-10 13:25
Check the last reply on https://github.com/2BAB/ScratchPaper/issues/3 , add enableAapt2 can fix it.

**Comment by 2BAB** [comment] 2018-10-10 13:36
Duplicate of #3

**Comment by 2BAB** [comment] 2018-10-10 13:37
If you meet some other problems please create a new issue, thank you.

**Closed as completed by 2BAB** 2018-10-10 13:37 UTC
Labels: duplicate
